blank_issues_enabled: false
contact_links:
- name: Nitrox Unlocked Discord server
  url: https://discord.gg/b8vE6zeWSy
  about: Please ask here for help if you have problems with setting up or using Nitrox Unlocked Mod.